[package]
name = "sqlite_storage"
version.workspace = true
edition = "2024"
license = "MulanPSL-2.0"

[dependencies]
model_core = { path = "../../../core/model" }
rusqlite = { version = "0.31.0", features = ["bundled"] }
storage_core = { path = "../../core" }
semantic_action_contract = { path = "../../../contracts/semantic_action" }
